"""deleted default uuid clause

Revision ID: 0327ac5ce9b0
Revises: 523c4a66b055
Create Date: 2021-12-20 04:47:04.807529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0327ac5ce9b0'
down_revision = '523c4a66b055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
