"""Add admin_user column in customers

Revision ID: 3477f93be37d
Revises: 4a4feed5fd9c
Create Date: 2022-03-06 19:00:49.674713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3477f93be37d'
down_revision = '4a4feed5fd9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('admin_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('admin_user_id', 'customers', 'users', ['admin_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_user_id', 'customers', type_='foreignkey')
    op.drop_column('customers', 'admin_user_id')
    # ### end Alembic commands ###
