"""remove username from user

Revision ID: 5cadb60584c4
Revises: 3fcf38ab2ec0
Create Date: 2021-10-05 22:23:11.106154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cadb60584c4'
down_revision = '3fcf38ab2ec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
