"""empty message

Revision ID: 8594a534393e
Revises: 2820ffe5630d
Create Date: 2021-03-30 05:05:03.087027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8594a534393e'
down_revision = '2820ffe5630d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
