"""add/remove col from subs table

Revision ID: 8db1eac19c11
Revises: 3477f93be37d
Create Date: 2022-03-07 12:50:16.649827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db1eac19c11'
down_revision = '3477f93be37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_latest_invoice_id', sa.String(length=50), nullable=True))
    op.drop_column('subscriptions', 'stripe_latest_subscription_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_latest_subscription_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'stripe_latest_invoice_id')
    # ### end Alembic commands ###
