"""added log tables and relationships between logs and submissions

Revision ID: cee5d4c5f18c
Revises: 62f983ae0764
Create Date: 2022-01-27 21:53:25.720111

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cee5d4c5f18c'
down_revision = '62f983ae0764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', postgresql.UUID(), nullable=False),
    sa.Column('start_kilobytes', sa.Integer(), nullable=False),
    sa.Column('size_kilobytes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('upload_id', sa.Integer(), nullable=False),
    sa.Column('deletion_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['upload_id'], ['upload_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deletion_logs')
    op.drop_table('upload_logs')
    # ### end Alembic commands ###
