"""adding email column

Revision ID: cf6d32774b06
Revises: 7ee6da8c1b9b
Create Date: 2021-11-16 00:29:45.753621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6d32774b06'
down_revision = '7ee6da8c1b9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'email')
    # ### end Alembic commands ###
