"""add datetime to phi upload logs

Revision ID: e377087ee095
Revises: 8a7990b795d7
Create Date: 2022-02-01 16:33:10.413692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e377087ee095'
down_revision = '8a7990b795d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_logs', sa.Column('creation_time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('upload_logs', 'creation_time')
    # ### end Alembic commands ###
