"""Change user id from bigint to int

Revision ID: f3ca8ddaa113
Revises: 20f4128547e6
Create Date: 2021-12-30 00:38:05.883888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ca8ddaa113'
down_revision = '20f4128547e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
