"""Add file size to submissions table

Revision ID: f5f7df1cda68
Revises: 4894c2066667
Create Date: 2022-04-21 17:24:17.606324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f7df1cda68'
down_revision = '4894c2066667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('file_size', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'file_size')
    # ### end Alembic commands ###
