"""create tables: customers, subs, invoices

Revision ID: 33323149a317
Revises: 26ac9eb27529
Create Date: 2022-03-08 12:09:41.251355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33323149a317'
down_revision = '26ac9eb27529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=50), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('admin_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('plan_description', sa.String(length=50), nullable=False),
    sa.Column('initial_start_date', sa.DateTime(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('cancel_date', sa.DateTime(), nullable=True),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=50), nullable=False),
    sa.Column('stripe_latest_invoice_id', sa.String(length=50), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=50), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=50), nullable=False),
    sa.Column('stripe_default_payment_method_id', sa.String(length=50), nullable=True),
    sa.Column('payment_card_type', sa.String(length=50), nullable=True),
    sa.Column('card_last4', sa.String(length=50), nullable=True),
    sa.Column('card_expiry', sa.String(length=50), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=50), nullable=False),
    sa.Column('payment_card_type', sa.String(length=50), nullable=True),
    sa.Column('payment_card_last4', sa.String(length=50), nullable=True),
    sa.Column('payment_card_expiry', sa.String(length=50), nullable=True),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=50), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(length=50), nullable=True),
    sa.Column('stripe_invoice_url', sa.String(length=200), nullable=True),
    sa.Column('stripe_invoice_number', sa.String(length=50), nullable=True),
    sa.Column('stripe_payment_receipt_url', sa.String(length=200), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoices')
    op.drop_table('subscriptions')
    op.drop_table('customers')
    # ### end Alembic commands ###
