"""add finished date to submissions table

Revision ID: 26ac9eb27529
Revises: e377087ee095
Create Date: 2022-02-25 00:09:26.853553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26ac9eb27529'
down_revision = 'e377087ee095'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('finished_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'finished_date')
    # ### end Alembic commands ###
