"""Add enum type to status

Revision ID: 59cf4558b77c
Revises: 706716e9c98d
Create Date: 2023-09-27 22:38:49.485037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '59cf4558b77c'
down_revision = '706716e9c98d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('submissions', sa.Column('workflow_id', sa.String(), nullable=False))
    op.drop_column('submissions', 'status')

    status_enum = postgresql.ENUM('CREATED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'ERROR', 'CLEANING_UP', 'FINISHED', name='submissionstatus')
    status_enum.create(op.get_bind(), checkfirst=False)  # Create ENUM type explicitly
    op.add_column('submissions', sa.Column('status', status_enum, nullable=False))
    
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.drop_column('submissions', 'pipeline')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('pipeline', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.alter_column('submissions', 'status',
               existing_type=postgresql.ENUM('CREATED', 'QUEUED', 'PROCESSING', 'COMPLETED', 'ERROR', 'CLEANING_UP', 'FINISHED', name='submissionstatus'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('submissions', 'workflow_id')
    # ### end Alembic commands ###
