"""added ability for panel to be nullable

Revision ID: 7ee6da8c1b9b
Revises: 429adf37ce04
Create Date: 2021-10-30 20:27:31.523109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee6da8c1b9b'
down_revision = '429adf37ce04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
