"""add plans table

Revision ID: 5854452b8222
Revises: ef098a228abe
Create Date: 2022-03-28 17:21:35.378423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5854452b8222'
down_revision = 'ef098a228abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('data_limit', sa.Float(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_time', sa.DateTime(), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('subscriptions', sa.Column('allow_downgrade', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('plan_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key('plan_id_fk', 'subscriptions', 'plans', ['plan_id'], ['id'])
    op.drop_column('subscriptions', 'stripe_price_id')
    op.drop_column('subscriptions', 'plan_description')
    op.drop_column('subscriptions', 'stripe_customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('stripe_customer_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('plan_description', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_price_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint('plan_id_fk', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'plan_id')
    op.drop_column('subscriptions', 'allow_downgrade')
    op.drop_table('plans')
    # ### end Alembic commands ###
