"""Added email and data usage dates to submissions

Revision ID: 20b52c03a11a
Revises: f5f7df1cda68
Create Date: 2022-04-27 14:11:38.766554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20b52c03a11a'
down_revision = 'f5f7df1cda68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('data_usage_updated_date', sa.DateTime(), nullable=True))
    op.add_column('submissions', sa.Column('email_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'email_date')
    op.drop_column('submissions', 'data_usage_updated_date')
    # ### end Alembic commands ###
