"""Added data usage fields to subs table

Revision ID: 4894c2066667
Revises: bb780bc089bb
Create Date: 2022-04-19 18:54:17.287846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4894c2066667'
down_revision = 'bb780bc089bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('data_limit_mb', sa.Float(), nullable=True))
    op.add_column('subscriptions', sa.Column('data_used', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'data_used')
    op.drop_column('subscriptions', 'data_limit_mb')
    # ### end Alembic commands ###
