"""plans table tax columns

Revision ID: a1eae6cda3cf
Revises: b97feb775806
Create Date: 2022-04-12 15:59:28.054690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1eae6cda3cf'
down_revision = 'b97feb775806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('tax_rate', sa.Integer(), nullable=True))
    op.add_column('plans', sa.Column('base_price', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('data_limit_mb', sa.Float(), nullable=False))
    op.add_column('plans', sa.Column('tax_amount', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('tax_rate', sa.Integer(), nullable=False))
    op.add_column('plans', sa.Column('total_price', sa.Integer(), nullable=False))
    op.drop_column('plans', 'price')
    op.drop_column('plans', 'data_limit')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('data_limit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'total_price')
    op.drop_column('plans', 'tax_rate')
    op.drop_column('plans', 'tax_amount')
    op.drop_column('plans', 'data_limit_mb')
    op.drop_column('plans', 'base_price')
    op.drop_column('customers', 'tax_rate')
    # ### end Alembic commands ###
