"""add cols for sub plan changes

Revision ID: b97feb775806
Revises: 5854452b8222
Create Date: 2022-03-29 17:26:20.620422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b97feb775806'
down_revision = '5854452b8222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('scheduled_plan_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_schedule_id', sa.String(length=50), nullable=True))
    op.create_foreign_key('scheduled_plan_id_fk', 'subscriptions', 'plans', ['scheduled_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scheduled_plan_id_fk', 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'stripe_schedule_id')
    op.drop_column('subscriptions', 'scheduled_plan_id')
    # ### end Alembic commands ###
