"""add isPaid col to subscriptions

Revision ID: c2468c79db5b
Revises: 0172ab12c224
Create Date: 2022-03-20 11:33:39.888604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2468c79db5b'
down_revision = '0172ab12c224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('is_paid', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'is_paid')
    # ### end Alembic commands ###
