"""updated tables to new tusd model

Revision ID: e7f9168b3325
Revises: 20b52c03a11a
Create Date: 2022-12-23 07:35:11.419459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e7f9168b3325'
down_revision = '20b52c03a11a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('pipeline', sa.String(), nullable=True))
    op.add_column('submissions', sa.Column('items', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('submissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('submissions', 'data_usage_updated_date')
    op.drop_column('submissions', 'panel')
    op.drop_column('submissions', 'email_date')
    op.drop_column('submissions', 'result')
    op.drop_column('submissions', 'file_size')
    op.drop_column('submissions', 'submission_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('submission_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('file_size', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('submissions', sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('email_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('panel', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('submissions', sa.Column('data_usage_updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('submissions', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('submissions', 'items')
    op.drop_column('submissions', 'pipeline')
    # ### end Alembic commands ###
