"""switch payment fields to customer table

Revision ID: 61029a07e5fc
Revises: c2468c79db5b
Create Date: 2022-03-22 17:24:17.185044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61029a07e5fc'
down_revision = 'c2468c79db5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('card_expiry', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('card_last4', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('payment_card_type', sa.String(length=50), nullable=True))
    op.add_column('customers', sa.Column('stripe_default_payment_method_id', sa.String(length=50), nullable=True))
    op.drop_column('subscriptions', 'payment_card_type')
    op.drop_column('subscriptions', 'card_expiry')
    op.drop_column('subscriptions', 'stripe_default_payment_method_id')
    op.drop_column('subscriptions', 'card_last4')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('card_last4', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('stripe_default_payment_method_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('card_expiry', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('subscriptions', sa.Column('payment_card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('customers', 'stripe_default_payment_method_id')
    op.drop_column('customers', 'payment_card_type')
    op.drop_column('customers', 'card_last4')
    op.drop_column('customers', 'card_expiry')
    # ### end Alembic commands ###
