version: '3.7'
services: 
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8080
    tty: true
    depends_on: 
      - postgres
    ports:
       - 8080:8080
    volumes:
      - ./backend:/app
      - ./backend/indexes:/app/indexes 
    environment:
      # PYTHONPATH: .
      DATABASE_URL: 'postgresql://aligndx:password@postgres:5432/aligndx_dev' 

  postgres:
    image: postgres:12
    restart: unless-stopped 
    environment:
      - POSTGRES_USER=aligndx
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=aligndx_dev
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data 

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=manjothunjan@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8001:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
      - postgres:pgsql-server
   

volumes:
  db-data: 
  pgadmin-data:

