"""dropping token_id field

Revision ID: 94da022d66c6
Revises: 699f239a0d8a
Create Date: 2021-03-30 18:12:35.885258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94da022d66c6'
down_revision = '699f239a0d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('token', sa.String(length=50), nullable=False))
    op.drop_column('samples', 'token_id')
    op.drop_column('samples', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('test', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('samples', sa.Column('token_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('samples', 'token')
    # ### end Alembic commands ###
