"""empty message

Revision ID: 9d5852c7b06e
Revises: e39e090b76b4
Create Date: 2021-03-30 18:03:49.174096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d5852c7b06e'
down_revision = 'e39e090b76b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
