"""empty message

Revision ID: e39e090b76b4
Revises: 8594a534393e
Create Date: 2021-03-30 17:39:17.570694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39e090b76b4'
down_revision = '8594a534393e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
