export { default as LoginView } from './login-view'
export { default as RegisterView } from './register-view'
export { default as ResetPasswordView } from './reset-password-view'
export { default as ForgotPasswordView } from './forgot-password-view'
export { default as ActivateView } from './activate-view'
